import type { Theme } from '@/contexts/ThemeContext'

type MermaidVars = Record<string, string>

// primaryTextColor is used by mermaid for ALL chart text (title, labels, legend).
// Set it to the theme foreground so every text element is readable on the background.
const MERMAID_VARS: Record<Theme, MermaidVars> = {
  morning: {
    primaryColor: '#8b5e3c',
    primaryTextColor: '#3d2b1f',
    pieTitleTextColor: '#3d2b1f',
    primaryBorderColor: '#6d4a30',
    lineColor: '#8c7a6b',
    secondaryColor: '#f0e6d8',
    tertiaryColor: '#f5ece0',
    background: 'transparent',
    mainBkg: 'transparent',
    cScale0: '#e74c3c',
    cScale1: '#2ecc71',
    cScale2: '#9b59b6',
    cScale3: '#f39c12',
    cScale4: '#1abc9c',
    cScale5: '#e91e63',
    cScale6: '#3498db',
    cScale7: '#ff5722',
  },
  afternoon: {
    primaryColor: '#3b82f6',
    primaryTextColor: '#0a0a0a',
    pieTitleTextColor: '#0a0a0a',
    primaryBorderColor: '#2563eb',
    lineColor: '#64748b',
    secondaryColor: '#f1f5f9',
    tertiaryColor: '#e2e8f0',
    background: 'transparent',
    mainBkg: 'transparent',
    cScale0: '#ef4444',
    cScale1: '#10b981',
    cScale2: '#8b5cf6',
    cScale3: '#f97316',
    cScale4: '#06b6d4',
    cScale5: '#ec4899',
    cScale6: '#84cc16',
    cScale7: '#f59e0b',
  },
  evening: {
    primaryColor: '#7b8fbd',
    primaryTextColor: '#c8cdd8',
    pieTitleTextColor: '#c8cdd8',
    primaryBorderColor: '#5a7299',
    lineColor: '#7a8399',
    secondaryColor: '#2a3145',
    tertiaryColor: '#242b3d',
    background: 'transparent',
    mainBkg: 'transparent',
    cScale0: '#e879f9',
    cScale1: '#22d3ee',
    cScale2: '#4ade80',
    cScale3: '#fb923c',
    cScale4: '#a78bfa',
    cScale5: '#f472b6',
    cScale6: '#fbbf24',
    cScale7: '#34d399',
  },
  night: {
    primaryColor: '#60a5fa',
    primaryTextColor: '#fafafa',
    pieTitleTextColor: '#fafafa',
    textColor: '#fafafa',
    primaryBorderColor: '#3b82f6',
    lineColor: '#94a3b8',
    secondaryColor: '#27272a',
    tertiaryColor: '#1e293b',
    background: 'transparent',
    mainBkg: 'transparent',
    cScale0: '#f43f5e',
    cScale1: '#a855f7',
    cScale2: '#06b6d4',
    cScale3: '#84cc16',
    cScale4: '#fb923c',
    cScale5: '#ec4899',
    cScale6: '#22d3ee',
    cScale7: '#a3e635',
  },
}

export function getMermaidVars(theme: Theme): MermaidVars {
  return MERMAID_VARS[theme]
}
